/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiDeviceSiteGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceSiteGet200Response{}

// ApiDeviceSiteGet200Response struct for ApiDeviceSiteGet200Response
type ApiDeviceSiteGet200Response struct {
	DeviceName *string `json:"deviceName,omitempty"`
	Location *string `json:"location,omitempty"`
	Position *string `json:"position,omitempty"`
}

// NewApiDeviceSiteGet200Response instantiates a new ApiDeviceSiteGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceSiteGet200Response() *ApiDeviceSiteGet200Response {
	this := ApiDeviceSiteGet200Response{}
	var deviceName string = "TCCM"
	this.DeviceName = &deviceName
	var location string = "Room"
	this.Location = &location
	var position string = "over central table"
	this.Position = &position
	return &this
}

// NewApiDeviceSiteGet200ResponseWithDefaults instantiates a new ApiDeviceSiteGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceSiteGet200ResponseWithDefaults() *ApiDeviceSiteGet200Response {
	this := ApiDeviceSiteGet200Response{}
	var deviceName string = "TCCM"
	this.DeviceName = &deviceName
	var location string = "Room"
	this.Location = &location
	var position string = "over central table"
	this.Position = &position
	return &this
}

// GetDeviceName returns the DeviceName field value if set, zero value otherwise.
func (o *ApiDeviceSiteGet200Response) GetDeviceName() string {
	if o == nil || IsNil(o.DeviceName) {
		var ret string
		return ret
	}
	return *o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceSiteGet200Response) GetDeviceNameOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceName) {
		return nil, false
	}
	return o.DeviceName, true
}

// HasDeviceName returns a boolean if a field has been set.
func (o *ApiDeviceSiteGet200Response) HasDeviceName() bool {
	if o != nil && !IsNil(o.DeviceName) {
		return true
	}

	return false
}

// SetDeviceName gets a reference to the given string and assigns it to the DeviceName field.
func (o *ApiDeviceSiteGet200Response) SetDeviceName(v string) {
	o.DeviceName = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ApiDeviceSiteGet200Response) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceSiteGet200Response) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ApiDeviceSiteGet200Response) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *ApiDeviceSiteGet200Response) SetLocation(v string) {
	o.Location = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *ApiDeviceSiteGet200Response) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceSiteGet200Response) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *ApiDeviceSiteGet200Response) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *ApiDeviceSiteGet200Response) SetPosition(v string) {
	o.Position = &v
}

func (o ApiDeviceSiteGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceSiteGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceName) {
		toSerialize["deviceName"] = o.DeviceName
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableApiDeviceSiteGet200Response struct {
	value *ApiDeviceSiteGet200Response
	isSet bool
}

func (v NullableApiDeviceSiteGet200Response) Get() *ApiDeviceSiteGet200Response {
	return v.value
}

func (v *NullableApiDeviceSiteGet200Response) Set(val *ApiDeviceSiteGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceSiteGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceSiteGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceSiteGet200Response(val *ApiDeviceSiteGet200Response) *NullableApiDeviceSiteGet200Response {
	return &NullableApiDeviceSiteGet200Response{value: val, isSet: true}
}

func (v NullableApiDeviceSiteGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceSiteGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


