/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation{}

// ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation struct for ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation
type ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation struct {
	// Angle in degrees
	Min *int32 `json:"min,omitempty"`
	// Angle in degrees
	Max *int32 `json:"max,omitempty"`
}

// NewApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation instantiates a new ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation() *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation {
	this := ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation{}
	return &this
}

// NewApiAudioInputsMicrophonePriorityZonesIdPutRequestElevationWithDefaults instantiates a new ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioInputsMicrophonePriorityZonesIdPutRequestElevationWithDefaults() *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation {
	this := ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation{}
	return &this
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) GetMin() int32 {
	if o == nil || IsNil(o.Min) {
		var ret int32
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) GetMinOk() (*int32, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given int32 and assigns it to the Min field.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) SetMin(v int32) {
	o.Min = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) GetMax() int32 {
	if o == nil || IsNil(o.Max) {
		var ret int32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) GetMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given int32 and assigns it to the Max field.
func (o *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) SetMax(v int32) {
	o.Max = &v
}

func (o ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	return toSerialize, nil
}

type NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation struct {
	value *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation
	isSet bool
}

func (v NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) Get() *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation {
	return v.value
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) Set(val *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation(val *ApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) *NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation {
	return &NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation{value: val, isSet: true}
}

func (v NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesIdPutRequestElevation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


