/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiSscStateSubscriptionsSessionUUIDAddPut400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSscStateSubscriptionsSessionUUIDAddPut400Response{}

// ApiSscStateSubscriptionsSessionUUIDAddPut400Response struct for ApiSscStateSubscriptionsSessionUUIDAddPut400Response
type ApiSscStateSubscriptionsSessionUUIDAddPut400Response struct {
	Path *string `json:"path,omitempty"`
	Error *int32 `json:"error,omitempty"`
}

// NewApiSscStateSubscriptionsSessionUUIDAddPut400Response instantiates a new ApiSscStateSubscriptionsSessionUUIDAddPut400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSscStateSubscriptionsSessionUUIDAddPut400Response() *ApiSscStateSubscriptionsSessionUUIDAddPut400Response {
	this := ApiSscStateSubscriptionsSessionUUIDAddPut400Response{}
	return &this
}

// NewApiSscStateSubscriptionsSessionUUIDAddPut400ResponseWithDefaults instantiates a new ApiSscStateSubscriptionsSessionUUIDAddPut400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSscStateSubscriptionsSessionUUIDAddPut400ResponseWithDefaults() *ApiSscStateSubscriptionsSessionUUIDAddPut400Response {
	this := ApiSscStateSubscriptionsSessionUUIDAddPut400Response{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) SetPath(v string) {
	o.Path = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) GetError() int32 {
	if o == nil || IsNil(o.Error) {
		var ret int32
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) GetErrorOk() (*int32, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given int32 and assigns it to the Error field.
func (o *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) SetError(v int32) {
	o.Error = &v
}

func (o ApiSscStateSubscriptionsSessionUUIDAddPut400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSscStateSubscriptionsSessionUUIDAddPut400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response struct {
	value *ApiSscStateSubscriptionsSessionUUIDAddPut400Response
	isSet bool
}

func (v NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response) Get() *ApiSscStateSubscriptionsSessionUUIDAddPut400Response {
	return v.value
}

func (v *NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response) Set(val *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSscStateSubscriptionsSessionUUIDAddPut400Response(val *ApiSscStateSubscriptionsSessionUUIDAddPut400Response) *NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response {
	return &NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response{value: val, isSet: true}
}

func (v NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSscStateSubscriptionsSessionUUIDAddPut400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


