/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioNoiseGateGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioNoiseGateGet200Response{}

// ApiAudioNoiseGateGet200Response struct for ApiAudioNoiseGateGet200Response
type ApiAudioNoiseGateGet200Response struct {
	// Threshold in dB
	Threshold *int32 `json:"threshold,omitempty"`
	// Hold time in ms
	HoldTime *int32 `json:"holdTime,omitempty"`
}

// NewApiAudioNoiseGateGet200Response instantiates a new ApiAudioNoiseGateGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioNoiseGateGet200Response() *ApiAudioNoiseGateGet200Response {
	this := ApiAudioNoiseGateGet200Response{}
	var threshold int32 = -80
	this.Threshold = &threshold
	var holdTime int32 = 350
	this.HoldTime = &holdTime
	return &this
}

// NewApiAudioNoiseGateGet200ResponseWithDefaults instantiates a new ApiAudioNoiseGateGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioNoiseGateGet200ResponseWithDefaults() *ApiAudioNoiseGateGet200Response {
	this := ApiAudioNoiseGateGet200Response{}
	var threshold int32 = -80
	this.Threshold = &threshold
	var holdTime int32 = 350
	this.HoldTime = &holdTime
	return &this
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *ApiAudioNoiseGateGet200Response) GetThreshold() int32 {
	if o == nil || IsNil(o.Threshold) {
		var ret int32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioNoiseGateGet200Response) GetThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *ApiAudioNoiseGateGet200Response) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int32 and assigns it to the Threshold field.
func (o *ApiAudioNoiseGateGet200Response) SetThreshold(v int32) {
	o.Threshold = &v
}

// GetHoldTime returns the HoldTime field value if set, zero value otherwise.
func (o *ApiAudioNoiseGateGet200Response) GetHoldTime() int32 {
	if o == nil || IsNil(o.HoldTime) {
		var ret int32
		return ret
	}
	return *o.HoldTime
}

// GetHoldTimeOk returns a tuple with the HoldTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioNoiseGateGet200Response) GetHoldTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.HoldTime) {
		return nil, false
	}
	return o.HoldTime, true
}

// HasHoldTime returns a boolean if a field has been set.
func (o *ApiAudioNoiseGateGet200Response) HasHoldTime() bool {
	if o != nil && !IsNil(o.HoldTime) {
		return true
	}

	return false
}

// SetHoldTime gets a reference to the given int32 and assigns it to the HoldTime field.
func (o *ApiAudioNoiseGateGet200Response) SetHoldTime(v int32) {
	o.HoldTime = &v
}

func (o ApiAudioNoiseGateGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioNoiseGateGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.HoldTime) {
		toSerialize["holdTime"] = o.HoldTime
	}
	return toSerialize, nil
}

type NullableApiAudioNoiseGateGet200Response struct {
	value *ApiAudioNoiseGateGet200Response
	isSet bool
}

func (v NullableApiAudioNoiseGateGet200Response) Get() *ApiAudioNoiseGateGet200Response {
	return v.value
}

func (v *NullableApiAudioNoiseGateGet200Response) Set(val *ApiAudioNoiseGateGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioNoiseGateGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioNoiseGateGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioNoiseGateGet200Response(val *ApiAudioNoiseGateGet200Response) *NullableApiAudioNoiseGateGet200Response {
	return &NullableApiAudioNoiseGateGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioNoiseGateGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioNoiseGateGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


