/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioInputsMicrophonePriorityZonesIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioInputsMicrophonePriorityZonesIdGet200Response{}

// ApiAudioInputsMicrophonePriorityZonesIdGet200Response struct for ApiAudioInputsMicrophonePriorityZonesIdGet200Response
type ApiAudioInputsMicrophonePriorityZonesIdGet200Response struct {
	Enabled *bool `json:"enabled,omitempty"`
	// Unitless multiplicator
	Weight *float32 `json:"weight,omitempty"`
	Elevation *ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseElevation `json:"elevation,omitempty"`
	Azimuth *ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseAzimuth `json:"azimuth,omitempty"`
}

// NewApiAudioInputsMicrophonePriorityZonesIdGet200Response instantiates a new ApiAudioInputsMicrophonePriorityZonesIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioInputsMicrophonePriorityZonesIdGet200Response() *ApiAudioInputsMicrophonePriorityZonesIdGet200Response {
	this := ApiAudioInputsMicrophonePriorityZonesIdGet200Response{}
	return &this
}

// NewApiAudioInputsMicrophonePriorityZonesIdGet200ResponseWithDefaults instantiates a new ApiAudioInputsMicrophonePriorityZonesIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioInputsMicrophonePriorityZonesIdGet200ResponseWithDefaults() *ApiAudioInputsMicrophonePriorityZonesIdGet200Response {
	this := ApiAudioInputsMicrophonePriorityZonesIdGet200Response{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetWeight() float32 {
	if o == nil || IsNil(o.Weight) {
		var ret float32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given float32 and assigns it to the Weight field.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) SetWeight(v float32) {
	o.Weight = &v
}

// GetElevation returns the Elevation field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetElevation() ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseElevation {
	if o == nil || IsNil(o.Elevation) {
		var ret ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseElevation
		return ret
	}
	return *o.Elevation
}

// GetElevationOk returns a tuple with the Elevation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetElevationOk() (*ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseElevation, bool) {
	if o == nil || IsNil(o.Elevation) {
		return nil, false
	}
	return o.Elevation, true
}

// HasElevation returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) HasElevation() bool {
	if o != nil && !IsNil(o.Elevation) {
		return true
	}

	return false
}

// SetElevation gets a reference to the given ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseElevation and assigns it to the Elevation field.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) SetElevation(v ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseElevation) {
	o.Elevation = &v
}

// GetAzimuth returns the Azimuth field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetAzimuth() ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseAzimuth {
	if o == nil || IsNil(o.Azimuth) {
		var ret ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseAzimuth
		return ret
	}
	return *o.Azimuth
}

// GetAzimuthOk returns a tuple with the Azimuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) GetAzimuthOk() (*ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseAzimuth, bool) {
	if o == nil || IsNil(o.Azimuth) {
		return nil, false
	}
	return o.Azimuth, true
}

// HasAzimuth returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) HasAzimuth() bool {
	if o != nil && !IsNil(o.Azimuth) {
		return true
	}

	return false
}

// SetAzimuth gets a reference to the given ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseAzimuth and assigns it to the Azimuth field.
func (o *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) SetAzimuth(v ApiAudioInputsMicrophoneExclusionZonesIdGet200ResponseAzimuth) {
	o.Azimuth = &v
}

func (o ApiAudioInputsMicrophonePriorityZonesIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioInputsMicrophonePriorityZonesIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	if !IsNil(o.Elevation) {
		toSerialize["elevation"] = o.Elevation
	}
	if !IsNil(o.Azimuth) {
		toSerialize["azimuth"] = o.Azimuth
	}
	return toSerialize, nil
}

type NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response struct {
	value *ApiAudioInputsMicrophonePriorityZonesIdGet200Response
	isSet bool
}

func (v NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response) Get() *ApiAudioInputsMicrophonePriorityZonesIdGet200Response {
	return v.value
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response) Set(val *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioInputsMicrophonePriorityZonesIdGet200Response(val *ApiAudioInputsMicrophonePriorityZonesIdGet200Response) *NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response {
	return &NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


