/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiDeviceLedsRingPutRequestMicOn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceLedsRingPutRequestMicOn{}

// ApiDeviceLedsRingPutRequestMicOn struct for ApiDeviceLedsRingPutRequestMicOn
type ApiDeviceLedsRingPutRequestMicOn struct {
	Color *string `json:"color,omitempty"`
}

// NewApiDeviceLedsRingPutRequestMicOn instantiates a new ApiDeviceLedsRingPutRequestMicOn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceLedsRingPutRequestMicOn() *ApiDeviceLedsRingPutRequestMicOn {
	this := ApiDeviceLedsRingPutRequestMicOn{}
	return &this
}

// NewApiDeviceLedsRingPutRequestMicOnWithDefaults instantiates a new ApiDeviceLedsRingPutRequestMicOn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceLedsRingPutRequestMicOnWithDefaults() *ApiDeviceLedsRingPutRequestMicOn {
	this := ApiDeviceLedsRingPutRequestMicOn{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequestMicOn) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequestMicOn) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequestMicOn) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ApiDeviceLedsRingPutRequestMicOn) SetColor(v string) {
	o.Color = &v
}

func (o ApiDeviceLedsRingPutRequestMicOn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceLedsRingPutRequestMicOn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

type NullableApiDeviceLedsRingPutRequestMicOn struct {
	value *ApiDeviceLedsRingPutRequestMicOn
	isSet bool
}

func (v NullableApiDeviceLedsRingPutRequestMicOn) Get() *ApiDeviceLedsRingPutRequestMicOn {
	return v.value
}

func (v *NullableApiDeviceLedsRingPutRequestMicOn) Set(val *ApiDeviceLedsRingPutRequestMicOn) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceLedsRingPutRequestMicOn) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceLedsRingPutRequestMicOn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceLedsRingPutRequestMicOn(val *ApiDeviceLedsRingPutRequestMicOn) *NullableApiDeviceLedsRingPutRequestMicOn {
	return &NullableApiDeviceLedsRingPutRequestMicOn{value: val, isSet: true}
}

func (v NullableApiDeviceLedsRingPutRequestMicOn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceLedsRingPutRequestMicOn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


