/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioInputsMicrophoneLevelGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioInputsMicrophoneLevelGet200Response{}

// ApiAudioInputsMicrophoneLevelGet200Response struct for ApiAudioInputsMicrophoneLevelGet200Response
type ApiAudioInputsMicrophoneLevelGet200Response struct {
	// Microphone peak level in dB
	Peak *int32 `json:"peak,omitempty"`
}

// NewApiAudioInputsMicrophoneLevelGet200Response instantiates a new ApiAudioInputsMicrophoneLevelGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioInputsMicrophoneLevelGet200Response() *ApiAudioInputsMicrophoneLevelGet200Response {
	this := ApiAudioInputsMicrophoneLevelGet200Response{}
	return &this
}

// NewApiAudioInputsMicrophoneLevelGet200ResponseWithDefaults instantiates a new ApiAudioInputsMicrophoneLevelGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioInputsMicrophoneLevelGet200ResponseWithDefaults() *ApiAudioInputsMicrophoneLevelGet200Response {
	this := ApiAudioInputsMicrophoneLevelGet200Response{}
	return &this
}

// GetPeak returns the Peak field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophoneLevelGet200Response) GetPeak() int32 {
	if o == nil || IsNil(o.Peak) {
		var ret int32
		return ret
	}
	return *o.Peak
}

// GetPeakOk returns a tuple with the Peak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophoneLevelGet200Response) GetPeakOk() (*int32, bool) {
	if o == nil || IsNil(o.Peak) {
		return nil, false
	}
	return o.Peak, true
}

// HasPeak returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophoneLevelGet200Response) HasPeak() bool {
	if o != nil && !IsNil(o.Peak) {
		return true
	}

	return false
}

// SetPeak gets a reference to the given int32 and assigns it to the Peak field.
func (o *ApiAudioInputsMicrophoneLevelGet200Response) SetPeak(v int32) {
	o.Peak = &v
}

func (o ApiAudioInputsMicrophoneLevelGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioInputsMicrophoneLevelGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Peak) {
		toSerialize["peak"] = o.Peak
	}
	return toSerialize, nil
}

type NullableApiAudioInputsMicrophoneLevelGet200Response struct {
	value *ApiAudioInputsMicrophoneLevelGet200Response
	isSet bool
}

func (v NullableApiAudioInputsMicrophoneLevelGet200Response) Get() *ApiAudioInputsMicrophoneLevelGet200Response {
	return v.value
}

func (v *NullableApiAudioInputsMicrophoneLevelGet200Response) Set(val *ApiAudioInputsMicrophoneLevelGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioInputsMicrophoneLevelGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioInputsMicrophoneLevelGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioInputsMicrophoneLevelGet200Response(val *ApiAudioInputsMicrophoneLevelGet200Response) *NullableApiAudioInputsMicrophoneLevelGet200Response {
	return &NullableApiAudioInputsMicrophoneLevelGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioInputsMicrophoneLevelGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioInputsMicrophoneLevelGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


