/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioOutputsGlobalMutePutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioOutputsGlobalMutePutRequest{}

// ApiAudioOutputsGlobalMutePutRequest struct for ApiAudioOutputsGlobalMutePutRequest
type ApiAudioOutputsGlobalMutePutRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// NewApiAudioOutputsGlobalMutePutRequest instantiates a new ApiAudioOutputsGlobalMutePutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioOutputsGlobalMutePutRequest() *ApiAudioOutputsGlobalMutePutRequest {
	this := ApiAudioOutputsGlobalMutePutRequest{}
	return &this
}

// NewApiAudioOutputsGlobalMutePutRequestWithDefaults instantiates a new ApiAudioOutputsGlobalMutePutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioOutputsGlobalMutePutRequestWithDefaults() *ApiAudioOutputsGlobalMutePutRequest {
	this := ApiAudioOutputsGlobalMutePutRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiAudioOutputsGlobalMutePutRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsGlobalMutePutRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiAudioOutputsGlobalMutePutRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ApiAudioOutputsGlobalMutePutRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o ApiAudioOutputsGlobalMutePutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioOutputsGlobalMutePutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableApiAudioOutputsGlobalMutePutRequest struct {
	value *ApiAudioOutputsGlobalMutePutRequest
	isSet bool
}

func (v NullableApiAudioOutputsGlobalMutePutRequest) Get() *ApiAudioOutputsGlobalMutePutRequest {
	return v.value
}

func (v *NullableApiAudioOutputsGlobalMutePutRequest) Set(val *ApiAudioOutputsGlobalMutePutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioOutputsGlobalMutePutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioOutputsGlobalMutePutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioOutputsGlobalMutePutRequest(val *ApiAudioOutputsGlobalMutePutRequest) *NullableApiAudioOutputsGlobalMutePutRequest {
	return &NullableApiAudioOutputsGlobalMutePutRequest{value: val, isSet: true}
}

func (v NullableApiAudioOutputsGlobalMutePutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioOutputsGlobalMutePutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


