/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiDeviceLedsRingGet200ResponseMicCustom type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceLedsRingGet200ResponseMicCustom{}

// ApiDeviceLedsRingGet200ResponseMicCustom struct for ApiDeviceLedsRingGet200ResponseMicCustom
type ApiDeviceLedsRingGet200ResponseMicCustom struct {
	Enabled *bool `json:"enabled,omitempty"`
	Color *string `json:"color,omitempty"`
}

// NewApiDeviceLedsRingGet200ResponseMicCustom instantiates a new ApiDeviceLedsRingGet200ResponseMicCustom object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceLedsRingGet200ResponseMicCustom() *ApiDeviceLedsRingGet200ResponseMicCustom {
	this := ApiDeviceLedsRingGet200ResponseMicCustom{}
	var enabled bool = false
	this.Enabled = &enabled
	var color string = "Green"
	this.Color = &color
	return &this
}

// NewApiDeviceLedsRingGet200ResponseMicCustomWithDefaults instantiates a new ApiDeviceLedsRingGet200ResponseMicCustom object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceLedsRingGet200ResponseMicCustomWithDefaults() *ApiDeviceLedsRingGet200ResponseMicCustom {
	this := ApiDeviceLedsRingGet200ResponseMicCustom{}
	var enabled bool = false
	this.Enabled = &enabled
	var color string = "Green"
	this.Color = &color
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ApiDeviceLedsRingGet200ResponseMicCustom) SetColor(v string) {
	o.Color = &v
}

func (o ApiDeviceLedsRingGet200ResponseMicCustom) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceLedsRingGet200ResponseMicCustom) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

type NullableApiDeviceLedsRingGet200ResponseMicCustom struct {
	value *ApiDeviceLedsRingGet200ResponseMicCustom
	isSet bool
}

func (v NullableApiDeviceLedsRingGet200ResponseMicCustom) Get() *ApiDeviceLedsRingGet200ResponseMicCustom {
	return v.value
}

func (v *NullableApiDeviceLedsRingGet200ResponseMicCustom) Set(val *ApiDeviceLedsRingGet200ResponseMicCustom) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceLedsRingGet200ResponseMicCustom) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceLedsRingGet200ResponseMicCustom) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceLedsRingGet200ResponseMicCustom(val *ApiDeviceLedsRingGet200ResponseMicCustom) *NullableApiDeviceLedsRingGet200ResponseMicCustom {
	return &NullableApiDeviceLedsRingGet200ResponseMicCustom{value: val, isSet: true}
}

func (v NullableApiDeviceLedsRingGet200ResponseMicCustom) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceLedsRingGet200ResponseMicCustom) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


