/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioEqualizerGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioEqualizerGet200Response{}

// ApiAudioEqualizerGet200Response struct for ApiAudioEqualizerGet200Response
type ApiAudioEqualizerGet200Response struct {
	// Equalizer bands with cut-off frequencies of 125, 250, 500, 1000, 2000, 4000, 8000 and Q value of 1.4142
	Gains []int32 `json:"gains,omitempty"`
}

// NewApiAudioEqualizerGet200Response instantiates a new ApiAudioEqualizerGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioEqualizerGet200Response() *ApiAudioEqualizerGet200Response {
	this := ApiAudioEqualizerGet200Response{}
	return &this
}

// NewApiAudioEqualizerGet200ResponseWithDefaults instantiates a new ApiAudioEqualizerGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioEqualizerGet200ResponseWithDefaults() *ApiAudioEqualizerGet200Response {
	this := ApiAudioEqualizerGet200Response{}
	return &this
}

// GetGains returns the Gains field value if set, zero value otherwise.
func (o *ApiAudioEqualizerGet200Response) GetGains() []int32 {
	if o == nil || IsNil(o.Gains) {
		var ret []int32
		return ret
	}
	return o.Gains
}

// GetGainsOk returns a tuple with the Gains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioEqualizerGet200Response) GetGainsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Gains) {
		return nil, false
	}
	return o.Gains, true
}

// HasGains returns a boolean if a field has been set.
func (o *ApiAudioEqualizerGet200Response) HasGains() bool {
	if o != nil && !IsNil(o.Gains) {
		return true
	}

	return false
}

// SetGains gets a reference to the given []int32 and assigns it to the Gains field.
func (o *ApiAudioEqualizerGet200Response) SetGains(v []int32) {
	o.Gains = v
}

func (o ApiAudioEqualizerGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioEqualizerGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gains) {
		toSerialize["gains"] = o.Gains
	}
	return toSerialize, nil
}

type NullableApiAudioEqualizerGet200Response struct {
	value *ApiAudioEqualizerGet200Response
	isSet bool
}

func (v NullableApiAudioEqualizerGet200Response) Get() *ApiAudioEqualizerGet200Response {
	return v.value
}

func (v *NullableApiAudioEqualizerGet200Response) Set(val *ApiAudioEqualizerGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioEqualizerGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioEqualizerGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioEqualizerGet200Response(val *ApiAudioEqualizerGet200Response) *NullableApiAudioEqualizerGet200Response {
	return &NullableApiAudioEqualizerGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioEqualizerGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioEqualizerGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


