/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioRoomInUseGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioRoomInUseGet200Response{}

// ApiAudioRoomInUseGet200Response struct for ApiAudioRoomInUseGet200Response
type ApiAudioRoomInUseGet200Response struct {
	// Indication whether the room is considered to be in use
	Active *bool `json:"active,omitempty"`
}

// NewApiAudioRoomInUseGet200Response instantiates a new ApiAudioRoomInUseGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioRoomInUseGet200Response() *ApiAudioRoomInUseGet200Response {
	this := ApiAudioRoomInUseGet200Response{}
	return &this
}

// NewApiAudioRoomInUseGet200ResponseWithDefaults instantiates a new ApiAudioRoomInUseGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioRoomInUseGet200ResponseWithDefaults() *ApiAudioRoomInUseGet200Response {
	this := ApiAudioRoomInUseGet200Response{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ApiAudioRoomInUseGet200Response) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioRoomInUseGet200Response) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ApiAudioRoomInUseGet200Response) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ApiAudioRoomInUseGet200Response) SetActive(v bool) {
	o.Active = &v
}

func (o ApiAudioRoomInUseGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioRoomInUseGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	return toSerialize, nil
}

type NullableApiAudioRoomInUseGet200Response struct {
	value *ApiAudioRoomInUseGet200Response
	isSet bool
}

func (v NullableApiAudioRoomInUseGet200Response) Get() *ApiAudioRoomInUseGet200Response {
	return v.value
}

func (v *NullableApiAudioRoomInUseGet200Response) Set(val *ApiAudioRoomInUseGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioRoomInUseGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioRoomInUseGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioRoomInUseGet200Response(val *ApiAudioRoomInUseGet200Response) *NullableApiAudioRoomInUseGet200Response {
	return &NullableApiAudioRoomInUseGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioRoomInUseGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioRoomInUseGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


