/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioEqualizerPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioEqualizerPutRequest{}

// ApiAudioEqualizerPutRequest struct for ApiAudioEqualizerPutRequest
type ApiAudioEqualizerPutRequest struct {
	// Equalizer bands with cut-off frequencies of 125, 250, 500, 1000, 2000, 4000, 8000 and Q value of 1.4142
	Gains []int32 `json:"gains,omitempty"`
}

// NewApiAudioEqualizerPutRequest instantiates a new ApiAudioEqualizerPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioEqualizerPutRequest() *ApiAudioEqualizerPutRequest {
	this := ApiAudioEqualizerPutRequest{}
	return &this
}

// NewApiAudioEqualizerPutRequestWithDefaults instantiates a new ApiAudioEqualizerPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioEqualizerPutRequestWithDefaults() *ApiAudioEqualizerPutRequest {
	this := ApiAudioEqualizerPutRequest{}
	return &this
}

// GetGains returns the Gains field value if set, zero value otherwise.
func (o *ApiAudioEqualizerPutRequest) GetGains() []int32 {
	if o == nil || IsNil(o.Gains) {
		var ret []int32
		return ret
	}
	return o.Gains
}

// GetGainsOk returns a tuple with the Gains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioEqualizerPutRequest) GetGainsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Gains) {
		return nil, false
	}
	return o.Gains, true
}

// HasGains returns a boolean if a field has been set.
func (o *ApiAudioEqualizerPutRequest) HasGains() bool {
	if o != nil && !IsNil(o.Gains) {
		return true
	}

	return false
}

// SetGains gets a reference to the given []int32 and assigns it to the Gains field.
func (o *ApiAudioEqualizerPutRequest) SetGains(v []int32) {
	o.Gains = v
}

func (o ApiAudioEqualizerPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioEqualizerPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gains) {
		toSerialize["gains"] = o.Gains
	}
	return toSerialize, nil
}

type NullableApiAudioEqualizerPutRequest struct {
	value *ApiAudioEqualizerPutRequest
	isSet bool
}

func (v NullableApiAudioEqualizerPutRequest) Get() *ApiAudioEqualizerPutRequest {
	return v.value
}

func (v *NullableApiAudioEqualizerPutRequest) Set(val *ApiAudioEqualizerPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioEqualizerPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioEqualizerPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioEqualizerPutRequest(val *ApiAudioEqualizerPutRequest) *NullableApiAudioEqualizerPutRequest {
	return &NullableApiAudioEqualizerPutRequest{value: val, isSet: true}
}

func (v NullableApiAudioEqualizerPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioEqualizerPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


