/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioVoiceLiftGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioVoiceLiftGet200Response{}

// ApiAudioVoiceLiftGet200Response struct for ApiAudioVoiceLiftGet200Response
type ApiAudioVoiceLiftGet200Response struct {
	// Threshold in dB
	EmergencyMuteThreshold *int32 `json:"emergencyMuteThreshold,omitempty"`
	// Mute time in s
	EmergencyMuteTime *int32 `json:"emergencyMuteTime,omitempty"`
}

// NewApiAudioVoiceLiftGet200Response instantiates a new ApiAudioVoiceLiftGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioVoiceLiftGet200Response() *ApiAudioVoiceLiftGet200Response {
	this := ApiAudioVoiceLiftGet200Response{}
	var emergencyMuteThreshold int32 = -20
	this.EmergencyMuteThreshold = &emergencyMuteThreshold
	var emergencyMuteTime int32 = 3
	this.EmergencyMuteTime = &emergencyMuteTime
	return &this
}

// NewApiAudioVoiceLiftGet200ResponseWithDefaults instantiates a new ApiAudioVoiceLiftGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioVoiceLiftGet200ResponseWithDefaults() *ApiAudioVoiceLiftGet200Response {
	this := ApiAudioVoiceLiftGet200Response{}
	var emergencyMuteThreshold int32 = -20
	this.EmergencyMuteThreshold = &emergencyMuteThreshold
	var emergencyMuteTime int32 = 3
	this.EmergencyMuteTime = &emergencyMuteTime
	return &this
}

// GetEmergencyMuteThreshold returns the EmergencyMuteThreshold field value if set, zero value otherwise.
func (o *ApiAudioVoiceLiftGet200Response) GetEmergencyMuteThreshold() int32 {
	if o == nil || IsNil(o.EmergencyMuteThreshold) {
		var ret int32
		return ret
	}
	return *o.EmergencyMuteThreshold
}

// GetEmergencyMuteThresholdOk returns a tuple with the EmergencyMuteThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioVoiceLiftGet200Response) GetEmergencyMuteThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.EmergencyMuteThreshold) {
		return nil, false
	}
	return o.EmergencyMuteThreshold, true
}

// HasEmergencyMuteThreshold returns a boolean if a field has been set.
func (o *ApiAudioVoiceLiftGet200Response) HasEmergencyMuteThreshold() bool {
	if o != nil && !IsNil(o.EmergencyMuteThreshold) {
		return true
	}

	return false
}

// SetEmergencyMuteThreshold gets a reference to the given int32 and assigns it to the EmergencyMuteThreshold field.
func (o *ApiAudioVoiceLiftGet200Response) SetEmergencyMuteThreshold(v int32) {
	o.EmergencyMuteThreshold = &v
}

// GetEmergencyMuteTime returns the EmergencyMuteTime field value if set, zero value otherwise.
func (o *ApiAudioVoiceLiftGet200Response) GetEmergencyMuteTime() int32 {
	if o == nil || IsNil(o.EmergencyMuteTime) {
		var ret int32
		return ret
	}
	return *o.EmergencyMuteTime
}

// GetEmergencyMuteTimeOk returns a tuple with the EmergencyMuteTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioVoiceLiftGet200Response) GetEmergencyMuteTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.EmergencyMuteTime) {
		return nil, false
	}
	return o.EmergencyMuteTime, true
}

// HasEmergencyMuteTime returns a boolean if a field has been set.
func (o *ApiAudioVoiceLiftGet200Response) HasEmergencyMuteTime() bool {
	if o != nil && !IsNil(o.EmergencyMuteTime) {
		return true
	}

	return false
}

// SetEmergencyMuteTime gets a reference to the given int32 and assigns it to the EmergencyMuteTime field.
func (o *ApiAudioVoiceLiftGet200Response) SetEmergencyMuteTime(v int32) {
	o.EmergencyMuteTime = &v
}

func (o ApiAudioVoiceLiftGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioVoiceLiftGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EmergencyMuteThreshold) {
		toSerialize["emergencyMuteThreshold"] = o.EmergencyMuteThreshold
	}
	if !IsNil(o.EmergencyMuteTime) {
		toSerialize["emergencyMuteTime"] = o.EmergencyMuteTime
	}
	return toSerialize, nil
}

type NullableApiAudioVoiceLiftGet200Response struct {
	value *ApiAudioVoiceLiftGet200Response
	isSet bool
}

func (v NullableApiAudioVoiceLiftGet200Response) Get() *ApiAudioVoiceLiftGet200Response {
	return v.value
}

func (v *NullableApiAudioVoiceLiftGet200Response) Set(val *ApiAudioVoiceLiftGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioVoiceLiftGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioVoiceLiftGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioVoiceLiftGet200Response(val *ApiAudioVoiceLiftGet200Response) *NullableApiAudioVoiceLiftGet200Response {
	return &NullableApiAudioVoiceLiftGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioVoiceLiftGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioVoiceLiftGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


