/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioOutputsDanteLocalPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioOutputsDanteLocalPutRequest{}

// ApiAudioOutputsDanteLocalPutRequest struct for ApiAudioOutputsDanteLocalPutRequest
type ApiAudioOutputsDanteLocalPutRequest struct {
	Gain *int32 `json:"gain,omitempty"`
	NoiseGateEnabled *bool `json:"noiseGateEnabled,omitempty"`
	EqualizerEnabled *bool `json:"equalizerEnabled,omitempty"`
	VoiceLiftEnabled *bool `json:"voiceLiftEnabled,omitempty"`
	Delay *int32 `json:"delay,omitempty"`
}

// NewApiAudioOutputsDanteLocalPutRequest instantiates a new ApiAudioOutputsDanteLocalPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioOutputsDanteLocalPutRequest() *ApiAudioOutputsDanteLocalPutRequest {
	this := ApiAudioOutputsDanteLocalPutRequest{}
	return &this
}

// NewApiAudioOutputsDanteLocalPutRequestWithDefaults instantiates a new ApiAudioOutputsDanteLocalPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioOutputsDanteLocalPutRequestWithDefaults() *ApiAudioOutputsDanteLocalPutRequest {
	this := ApiAudioOutputsDanteLocalPutRequest{}
	return &this
}

// GetGain returns the Gain field value if set, zero value otherwise.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetGain() int32 {
	if o == nil || IsNil(o.Gain) {
		var ret int32
		return ret
	}
	return *o.Gain
}

// GetGainOk returns a tuple with the Gain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetGainOk() (*int32, bool) {
	if o == nil || IsNil(o.Gain) {
		return nil, false
	}
	return o.Gain, true
}

// HasGain returns a boolean if a field has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) HasGain() bool {
	if o != nil && !IsNil(o.Gain) {
		return true
	}

	return false
}

// SetGain gets a reference to the given int32 and assigns it to the Gain field.
func (o *ApiAudioOutputsDanteLocalPutRequest) SetGain(v int32) {
	o.Gain = &v
}

// GetNoiseGateEnabled returns the NoiseGateEnabled field value if set, zero value otherwise.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetNoiseGateEnabled() bool {
	if o == nil || IsNil(o.NoiseGateEnabled) {
		var ret bool
		return ret
	}
	return *o.NoiseGateEnabled
}

// GetNoiseGateEnabledOk returns a tuple with the NoiseGateEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetNoiseGateEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.NoiseGateEnabled) {
		return nil, false
	}
	return o.NoiseGateEnabled, true
}

// HasNoiseGateEnabled returns a boolean if a field has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) HasNoiseGateEnabled() bool {
	if o != nil && !IsNil(o.NoiseGateEnabled) {
		return true
	}

	return false
}

// SetNoiseGateEnabled gets a reference to the given bool and assigns it to the NoiseGateEnabled field.
func (o *ApiAudioOutputsDanteLocalPutRequest) SetNoiseGateEnabled(v bool) {
	o.NoiseGateEnabled = &v
}

// GetEqualizerEnabled returns the EqualizerEnabled field value if set, zero value otherwise.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetEqualizerEnabled() bool {
	if o == nil || IsNil(o.EqualizerEnabled) {
		var ret bool
		return ret
	}
	return *o.EqualizerEnabled
}

// GetEqualizerEnabledOk returns a tuple with the EqualizerEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetEqualizerEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.EqualizerEnabled) {
		return nil, false
	}
	return o.EqualizerEnabled, true
}

// HasEqualizerEnabled returns a boolean if a field has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) HasEqualizerEnabled() bool {
	if o != nil && !IsNil(o.EqualizerEnabled) {
		return true
	}

	return false
}

// SetEqualizerEnabled gets a reference to the given bool and assigns it to the EqualizerEnabled field.
func (o *ApiAudioOutputsDanteLocalPutRequest) SetEqualizerEnabled(v bool) {
	o.EqualizerEnabled = &v
}

// GetVoiceLiftEnabled returns the VoiceLiftEnabled field value if set, zero value otherwise.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetVoiceLiftEnabled() bool {
	if o == nil || IsNil(o.VoiceLiftEnabled) {
		var ret bool
		return ret
	}
	return *o.VoiceLiftEnabled
}

// GetVoiceLiftEnabledOk returns a tuple with the VoiceLiftEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetVoiceLiftEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.VoiceLiftEnabled) {
		return nil, false
	}
	return o.VoiceLiftEnabled, true
}

// HasVoiceLiftEnabled returns a boolean if a field has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) HasVoiceLiftEnabled() bool {
	if o != nil && !IsNil(o.VoiceLiftEnabled) {
		return true
	}

	return false
}

// SetVoiceLiftEnabled gets a reference to the given bool and assigns it to the VoiceLiftEnabled field.
func (o *ApiAudioOutputsDanteLocalPutRequest) SetVoiceLiftEnabled(v bool) {
	o.VoiceLiftEnabled = &v
}

// GetDelay returns the Delay field value if set, zero value otherwise.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetDelay() int32 {
	if o == nil || IsNil(o.Delay) {
		var ret int32
		return ret
	}
	return *o.Delay
}

// GetDelayOk returns a tuple with the Delay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) GetDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.Delay) {
		return nil, false
	}
	return o.Delay, true
}

// HasDelay returns a boolean if a field has been set.
func (o *ApiAudioOutputsDanteLocalPutRequest) HasDelay() bool {
	if o != nil && !IsNil(o.Delay) {
		return true
	}

	return false
}

// SetDelay gets a reference to the given int32 and assigns it to the Delay field.
func (o *ApiAudioOutputsDanteLocalPutRequest) SetDelay(v int32) {
	o.Delay = &v
}

func (o ApiAudioOutputsDanteLocalPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioOutputsDanteLocalPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gain) {
		toSerialize["gain"] = o.Gain
	}
	if !IsNil(o.NoiseGateEnabled) {
		toSerialize["noiseGateEnabled"] = o.NoiseGateEnabled
	}
	if !IsNil(o.EqualizerEnabled) {
		toSerialize["equalizerEnabled"] = o.EqualizerEnabled
	}
	if !IsNil(o.VoiceLiftEnabled) {
		toSerialize["voiceLiftEnabled"] = o.VoiceLiftEnabled
	}
	if !IsNil(o.Delay) {
		toSerialize["delay"] = o.Delay
	}
	return toSerialize, nil
}

type NullableApiAudioOutputsDanteLocalPutRequest struct {
	value *ApiAudioOutputsDanteLocalPutRequest
	isSet bool
}

func (v NullableApiAudioOutputsDanteLocalPutRequest) Get() *ApiAudioOutputsDanteLocalPutRequest {
	return v.value
}

func (v *NullableApiAudioOutputsDanteLocalPutRequest) Set(val *ApiAudioOutputsDanteLocalPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioOutputsDanteLocalPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioOutputsDanteLocalPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioOutputsDanteLocalPutRequest(val *ApiAudioOutputsDanteLocalPutRequest) *NullableApiAudioOutputsDanteLocalPutRequest {
	return &NullableApiAudioOutputsDanteLocalPutRequest{value: val, isSet: true}
}

func (v NullableApiAudioOutputsDanteLocalPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioOutputsDanteLocalPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


