/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation{}

// ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation struct for ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation
type ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation struct {
	// Angle in degrees
	Min *int32 `json:"min,omitempty"`
	// Angle in degrees
	Max *int32 `json:"max,omitempty"`
}

// NewApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation instantiates a new ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation() *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation {
	this := ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation{}
	return &this
}

// NewApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevationWithDefaults instantiates a new ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevationWithDefaults() *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation {
	this := ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation{}
	return &this
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) GetMin() int32 {
	if o == nil || IsNil(o.Min) {
		var ret int32
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) GetMinOk() (*int32, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given int32 and assigns it to the Min field.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) SetMin(v int32) {
	o.Min = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) GetMax() int32 {
	if o == nil || IsNil(o.Max) {
		var ret int32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) GetMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given int32 and assigns it to the Max field.
func (o *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) SetMax(v int32) {
	o.Max = &v
}

func (o ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	return toSerialize, nil
}

type NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation struct {
	value *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation
	isSet bool
}

func (v NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) Get() *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation {
	return v.value
}

func (v *NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) Set(val *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation(val *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) *NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation {
	return &NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation{value: val, isSet: true}
}

func (v NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


