/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioOutputsAnalogGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioOutputsAnalogGet200Response{}

// ApiAudioOutputsAnalogGet200Response struct for ApiAudioOutputsAnalogGet200Response
type ApiAudioOutputsAnalogGet200Response struct {
	// Gain in dB
	Gain *int32 `json:"gain,omitempty"`
	Switch *string `json:"switch,omitempty"`
}

// NewApiAudioOutputsAnalogGet200Response instantiates a new ApiAudioOutputsAnalogGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioOutputsAnalogGet200Response() *ApiAudioOutputsAnalogGet200Response {
	this := ApiAudioOutputsAnalogGet200Response{}
	var gain int32 = 0
	this.Gain = &gain
	var switch_ string = "FarendOutput"
	this.Switch = &switch_
	return &this
}

// NewApiAudioOutputsAnalogGet200ResponseWithDefaults instantiates a new ApiAudioOutputsAnalogGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioOutputsAnalogGet200ResponseWithDefaults() *ApiAudioOutputsAnalogGet200Response {
	this := ApiAudioOutputsAnalogGet200Response{}
	var gain int32 = 0
	this.Gain = &gain
	var switch_ string = "FarendOutput"
	this.Switch = &switch_
	return &this
}

// GetGain returns the Gain field value if set, zero value otherwise.
func (o *ApiAudioOutputsAnalogGet200Response) GetGain() int32 {
	if o == nil || IsNil(o.Gain) {
		var ret int32
		return ret
	}
	return *o.Gain
}

// GetGainOk returns a tuple with the Gain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsAnalogGet200Response) GetGainOk() (*int32, bool) {
	if o == nil || IsNil(o.Gain) {
		return nil, false
	}
	return o.Gain, true
}

// HasGain returns a boolean if a field has been set.
func (o *ApiAudioOutputsAnalogGet200Response) HasGain() bool {
	if o != nil && !IsNil(o.Gain) {
		return true
	}

	return false
}

// SetGain gets a reference to the given int32 and assigns it to the Gain field.
func (o *ApiAudioOutputsAnalogGet200Response) SetGain(v int32) {
	o.Gain = &v
}

// GetSwitch returns the Switch field value if set, zero value otherwise.
func (o *ApiAudioOutputsAnalogGet200Response) GetSwitch() string {
	if o == nil || IsNil(o.Switch) {
		var ret string
		return ret
	}
	return *o.Switch
}

// GetSwitchOk returns a tuple with the Switch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsAnalogGet200Response) GetSwitchOk() (*string, bool) {
	if o == nil || IsNil(o.Switch) {
		return nil, false
	}
	return o.Switch, true
}

// HasSwitch returns a boolean if a field has been set.
func (o *ApiAudioOutputsAnalogGet200Response) HasSwitch() bool {
	if o != nil && !IsNil(o.Switch) {
		return true
	}

	return false
}

// SetSwitch gets a reference to the given string and assigns it to the Switch field.
func (o *ApiAudioOutputsAnalogGet200Response) SetSwitch(v string) {
	o.Switch = &v
}

func (o ApiAudioOutputsAnalogGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioOutputsAnalogGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gain) {
		toSerialize["gain"] = o.Gain
	}
	if !IsNil(o.Switch) {
		toSerialize["switch"] = o.Switch
	}
	return toSerialize, nil
}

type NullableApiAudioOutputsAnalogGet200Response struct {
	value *ApiAudioOutputsAnalogGet200Response
	isSet bool
}

func (v NullableApiAudioOutputsAnalogGet200Response) Get() *ApiAudioOutputsAnalogGet200Response {
	return v.value
}

func (v *NullableApiAudioOutputsAnalogGet200Response) Set(val *ApiAudioOutputsAnalogGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioOutputsAnalogGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioOutputsAnalogGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioOutputsAnalogGet200Response(val *ApiAudioOutputsAnalogGet200Response) *NullableApiAudioOutputsAnalogGet200Response {
	return &NullableApiAudioOutputsAnalogGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioOutputsAnalogGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioOutputsAnalogGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


