/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioOutputsGlobalMuteGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioOutputsGlobalMuteGet200Response{}

// ApiAudioOutputsGlobalMuteGet200Response struct for ApiAudioOutputsGlobalMuteGet200Response
type ApiAudioOutputsGlobalMuteGet200Response struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// NewApiAudioOutputsGlobalMuteGet200Response instantiates a new ApiAudioOutputsGlobalMuteGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioOutputsGlobalMuteGet200Response() *ApiAudioOutputsGlobalMuteGet200Response {
	this := ApiAudioOutputsGlobalMuteGet200Response{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewApiAudioOutputsGlobalMuteGet200ResponseWithDefaults instantiates a new ApiAudioOutputsGlobalMuteGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioOutputsGlobalMuteGet200ResponseWithDefaults() *ApiAudioOutputsGlobalMuteGet200Response {
	this := ApiAudioOutputsGlobalMuteGet200Response{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiAudioOutputsGlobalMuteGet200Response) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsGlobalMuteGet200Response) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiAudioOutputsGlobalMuteGet200Response) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ApiAudioOutputsGlobalMuteGet200Response) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o ApiAudioOutputsGlobalMuteGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioOutputsGlobalMuteGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableApiAudioOutputsGlobalMuteGet200Response struct {
	value *ApiAudioOutputsGlobalMuteGet200Response
	isSet bool
}

func (v NullableApiAudioOutputsGlobalMuteGet200Response) Get() *ApiAudioOutputsGlobalMuteGet200Response {
	return v.value
}

func (v *NullableApiAudioOutputsGlobalMuteGet200Response) Set(val *ApiAudioOutputsGlobalMuteGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioOutputsGlobalMuteGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioOutputsGlobalMuteGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioOutputsGlobalMuteGet200Response(val *ApiAudioOutputsGlobalMuteGet200Response) *NullableApiAudioOutputsGlobalMuteGet200Response {
	return &NullableApiAudioOutputsGlobalMuteGet200Response{value: val, isSet: true}
}

func (v NullableApiAudioOutputsGlobalMuteGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioOutputsGlobalMuteGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


