/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiDeviceLedsRingGet200ResponseMicOn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceLedsRingGet200ResponseMicOn{}

// ApiDeviceLedsRingGet200ResponseMicOn struct for ApiDeviceLedsRingGet200ResponseMicOn
type ApiDeviceLedsRingGet200ResponseMicOn struct {
	Color *string `json:"color,omitempty"`
}

// NewApiDeviceLedsRingGet200ResponseMicOn instantiates a new ApiDeviceLedsRingGet200ResponseMicOn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceLedsRingGet200ResponseMicOn() *ApiDeviceLedsRingGet200ResponseMicOn {
	this := ApiDeviceLedsRingGet200ResponseMicOn{}
	var color string = "Green"
	this.Color = &color
	return &this
}

// NewApiDeviceLedsRingGet200ResponseMicOnWithDefaults instantiates a new ApiDeviceLedsRingGet200ResponseMicOn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceLedsRingGet200ResponseMicOnWithDefaults() *ApiDeviceLedsRingGet200ResponseMicOn {
	this := ApiDeviceLedsRingGet200ResponseMicOn{}
	var color string = "Green"
	this.Color = &color
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200ResponseMicOn) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200ResponseMicOn) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200ResponseMicOn) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ApiDeviceLedsRingGet200ResponseMicOn) SetColor(v string) {
	o.Color = &v
}

func (o ApiDeviceLedsRingGet200ResponseMicOn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceLedsRingGet200ResponseMicOn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

type NullableApiDeviceLedsRingGet200ResponseMicOn struct {
	value *ApiDeviceLedsRingGet200ResponseMicOn
	isSet bool
}

func (v NullableApiDeviceLedsRingGet200ResponseMicOn) Get() *ApiDeviceLedsRingGet200ResponseMicOn {
	return v.value
}

func (v *NullableApiDeviceLedsRingGet200ResponseMicOn) Set(val *ApiDeviceLedsRingGet200ResponseMicOn) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceLedsRingGet200ResponseMicOn) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceLedsRingGet200ResponseMicOn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceLedsRingGet200ResponseMicOn(val *ApiDeviceLedsRingGet200ResponseMicOn) *NullableApiDeviceLedsRingGet200ResponseMicOn {
	return &NullableApiDeviceLedsRingGet200ResponseMicOn{value: val, isSet: true}
}

func (v NullableApiDeviceLedsRingGet200ResponseMicOn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceLedsRingGet200ResponseMicOn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


