/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner{}

// ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner struct for ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner
type ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner struct {
	Id *int32 `json:"id,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	// Unitless multiplicator
	Weight *float32 `json:"weight,omitempty"`
	Elevation *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation `json:"elevation,omitempty"`
	Azimuth *ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerAzimuth `json:"azimuth,omitempty"`
}

// NewApiAudioInputsMicrophonePriorityZonesGet200ResponseInner instantiates a new ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioInputsMicrophonePriorityZonesGet200ResponseInner() *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner {
	this := ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner{}
	return &this
}

// NewApiAudioInputsMicrophonePriorityZonesGet200ResponseInnerWithDefaults instantiates a new ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioInputsMicrophonePriorityZonesGet200ResponseInnerWithDefaults() *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner {
	this := ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) SetId(v int32) {
	o.Id = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetWeight() float32 {
	if o == nil || IsNil(o.Weight) {
		var ret float32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given float32 and assigns it to the Weight field.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) SetWeight(v float32) {
	o.Weight = &v
}

// GetElevation returns the Elevation field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetElevation() ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation {
	if o == nil || IsNil(o.Elevation) {
		var ret ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation
		return ret
	}
	return *o.Elevation
}

// GetElevationOk returns a tuple with the Elevation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetElevationOk() (*ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation, bool) {
	if o == nil || IsNil(o.Elevation) {
		return nil, false
	}
	return o.Elevation, true
}

// HasElevation returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) HasElevation() bool {
	if o != nil && !IsNil(o.Elevation) {
		return true
	}

	return false
}

// SetElevation gets a reference to the given ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation and assigns it to the Elevation field.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) SetElevation(v ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerElevation) {
	o.Elevation = &v
}

// GetAzimuth returns the Azimuth field value if set, zero value otherwise.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetAzimuth() ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerAzimuth {
	if o == nil || IsNil(o.Azimuth) {
		var ret ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerAzimuth
		return ret
	}
	return *o.Azimuth
}

// GetAzimuthOk returns a tuple with the Azimuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) GetAzimuthOk() (*ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerAzimuth, bool) {
	if o == nil || IsNil(o.Azimuth) {
		return nil, false
	}
	return o.Azimuth, true
}

// HasAzimuth returns a boolean if a field has been set.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) HasAzimuth() bool {
	if o != nil && !IsNil(o.Azimuth) {
		return true
	}

	return false
}

// SetAzimuth gets a reference to the given ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerAzimuth and assigns it to the Azimuth field.
func (o *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) SetAzimuth(v ApiAudioInputsMicrophoneExclusionZonesGet200ResponseInnerAzimuth) {
	o.Azimuth = &v
}

func (o ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	if !IsNil(o.Elevation) {
		toSerialize["elevation"] = o.Elevation
	}
	if !IsNil(o.Azimuth) {
		toSerialize["azimuth"] = o.Azimuth
	}
	return toSerialize, nil
}

type NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner struct {
	value *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner
	isSet bool
}

func (v NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) Get() *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner {
	return v.value
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) Set(val *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner(val *ApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) *NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner {
	return &NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner{value: val, isSet: true}
}

func (v NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioInputsMicrophonePriorityZonesGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


