/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiDeviceLedsRingPutRequestMicCustom type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceLedsRingPutRequestMicCustom{}

// ApiDeviceLedsRingPutRequestMicCustom struct for ApiDeviceLedsRingPutRequestMicCustom
type ApiDeviceLedsRingPutRequestMicCustom struct {
	Enabled *bool `json:"enabled,omitempty"`
	Color *string `json:"color,omitempty"`
}

// NewApiDeviceLedsRingPutRequestMicCustom instantiates a new ApiDeviceLedsRingPutRequestMicCustom object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceLedsRingPutRequestMicCustom() *ApiDeviceLedsRingPutRequestMicCustom {
	this := ApiDeviceLedsRingPutRequestMicCustom{}
	return &this
}

// NewApiDeviceLedsRingPutRequestMicCustomWithDefaults instantiates a new ApiDeviceLedsRingPutRequestMicCustom object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceLedsRingPutRequestMicCustomWithDefaults() *ApiDeviceLedsRingPutRequestMicCustom {
	this := ApiDeviceLedsRingPutRequestMicCustom{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequestMicCustom) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequestMicCustom) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequestMicCustom) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ApiDeviceLedsRingPutRequestMicCustom) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequestMicCustom) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequestMicCustom) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequestMicCustom) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *ApiDeviceLedsRingPutRequestMicCustom) SetColor(v string) {
	o.Color = &v
}

func (o ApiDeviceLedsRingPutRequestMicCustom) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceLedsRingPutRequestMicCustom) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	return toSerialize, nil
}

type NullableApiDeviceLedsRingPutRequestMicCustom struct {
	value *ApiDeviceLedsRingPutRequestMicCustom
	isSet bool
}

func (v NullableApiDeviceLedsRingPutRequestMicCustom) Get() *ApiDeviceLedsRingPutRequestMicCustom {
	return v.value
}

func (v *NullableApiDeviceLedsRingPutRequestMicCustom) Set(val *ApiDeviceLedsRingPutRequestMicCustom) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceLedsRingPutRequestMicCustom) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceLedsRingPutRequestMicCustom) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceLedsRingPutRequestMicCustom(val *ApiDeviceLedsRingPutRequestMicCustom) *NullableApiDeviceLedsRingPutRequestMicCustom {
	return &NullableApiDeviceLedsRingPutRequestMicCustom{value: val, isSet: true}
}

func (v NullableApiDeviceLedsRingPutRequestMicCustom) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceLedsRingPutRequestMicCustom) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


