/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiDeviceLedsRingGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceLedsRingGet200Response{}

// ApiDeviceLedsRingGet200Response struct for ApiDeviceLedsRingGet200Response
type ApiDeviceLedsRingGet200Response struct {
	// The brightness of the led ring can be controlled in 6 steps, where 0 is off and 5 is full brightness.
	Brightness *int32 `json:"brightness,omitempty"`
	ShowFarendActivity *bool `json:"showFarendActivity,omitempty"`
	MicOn *ApiDeviceLedsRingGet200ResponseMicOn `json:"micOn,omitempty"`
	MicMute *ApiDeviceLedsRingGet200ResponseMicOn `json:"micMute,omitempty"`
	MicCustom *ApiDeviceLedsRingGet200ResponseMicCustom `json:"micCustom,omitempty"`
}

// NewApiDeviceLedsRingGet200Response instantiates a new ApiDeviceLedsRingGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceLedsRingGet200Response() *ApiDeviceLedsRingGet200Response {
	this := ApiDeviceLedsRingGet200Response{}
	var brightness int32 = 5
	this.Brightness = &brightness
	var showFarendActivity bool = false
	this.ShowFarendActivity = &showFarendActivity
	return &this
}

// NewApiDeviceLedsRingGet200ResponseWithDefaults instantiates a new ApiDeviceLedsRingGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceLedsRingGet200ResponseWithDefaults() *ApiDeviceLedsRingGet200Response {
	this := ApiDeviceLedsRingGet200Response{}
	var brightness int32 = 5
	this.Brightness = &brightness
	var showFarendActivity bool = false
	this.ShowFarendActivity = &showFarendActivity
	return &this
}

// GetBrightness returns the Brightness field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200Response) GetBrightness() int32 {
	if o == nil || IsNil(o.Brightness) {
		var ret int32
		return ret
	}
	return *o.Brightness
}

// GetBrightnessOk returns a tuple with the Brightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200Response) GetBrightnessOk() (*int32, bool) {
	if o == nil || IsNil(o.Brightness) {
		return nil, false
	}
	return o.Brightness, true
}

// HasBrightness returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200Response) HasBrightness() bool {
	if o != nil && !IsNil(o.Brightness) {
		return true
	}

	return false
}

// SetBrightness gets a reference to the given int32 and assigns it to the Brightness field.
func (o *ApiDeviceLedsRingGet200Response) SetBrightness(v int32) {
	o.Brightness = &v
}

// GetShowFarendActivity returns the ShowFarendActivity field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200Response) GetShowFarendActivity() bool {
	if o == nil || IsNil(o.ShowFarendActivity) {
		var ret bool
		return ret
	}
	return *o.ShowFarendActivity
}

// GetShowFarendActivityOk returns a tuple with the ShowFarendActivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200Response) GetShowFarendActivityOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowFarendActivity) {
		return nil, false
	}
	return o.ShowFarendActivity, true
}

// HasShowFarendActivity returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200Response) HasShowFarendActivity() bool {
	if o != nil && !IsNil(o.ShowFarendActivity) {
		return true
	}

	return false
}

// SetShowFarendActivity gets a reference to the given bool and assigns it to the ShowFarendActivity field.
func (o *ApiDeviceLedsRingGet200Response) SetShowFarendActivity(v bool) {
	o.ShowFarendActivity = &v
}

// GetMicOn returns the MicOn field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200Response) GetMicOn() ApiDeviceLedsRingGet200ResponseMicOn {
	if o == nil || IsNil(o.MicOn) {
		var ret ApiDeviceLedsRingGet200ResponseMicOn
		return ret
	}
	return *o.MicOn
}

// GetMicOnOk returns a tuple with the MicOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200Response) GetMicOnOk() (*ApiDeviceLedsRingGet200ResponseMicOn, bool) {
	if o == nil || IsNil(o.MicOn) {
		return nil, false
	}
	return o.MicOn, true
}

// HasMicOn returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200Response) HasMicOn() bool {
	if o != nil && !IsNil(o.MicOn) {
		return true
	}

	return false
}

// SetMicOn gets a reference to the given ApiDeviceLedsRingGet200ResponseMicOn and assigns it to the MicOn field.
func (o *ApiDeviceLedsRingGet200Response) SetMicOn(v ApiDeviceLedsRingGet200ResponseMicOn) {
	o.MicOn = &v
}

// GetMicMute returns the MicMute field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200Response) GetMicMute() ApiDeviceLedsRingGet200ResponseMicOn {
	if o == nil || IsNil(o.MicMute) {
		var ret ApiDeviceLedsRingGet200ResponseMicOn
		return ret
	}
	return *o.MicMute
}

// GetMicMuteOk returns a tuple with the MicMute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200Response) GetMicMuteOk() (*ApiDeviceLedsRingGet200ResponseMicOn, bool) {
	if o == nil || IsNil(o.MicMute) {
		return nil, false
	}
	return o.MicMute, true
}

// HasMicMute returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200Response) HasMicMute() bool {
	if o != nil && !IsNil(o.MicMute) {
		return true
	}

	return false
}

// SetMicMute gets a reference to the given ApiDeviceLedsRingGet200ResponseMicOn and assigns it to the MicMute field.
func (o *ApiDeviceLedsRingGet200Response) SetMicMute(v ApiDeviceLedsRingGet200ResponseMicOn) {
	o.MicMute = &v
}

// GetMicCustom returns the MicCustom field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingGet200Response) GetMicCustom() ApiDeviceLedsRingGet200ResponseMicCustom {
	if o == nil || IsNil(o.MicCustom) {
		var ret ApiDeviceLedsRingGet200ResponseMicCustom
		return ret
	}
	return *o.MicCustom
}

// GetMicCustomOk returns a tuple with the MicCustom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingGet200Response) GetMicCustomOk() (*ApiDeviceLedsRingGet200ResponseMicCustom, bool) {
	if o == nil || IsNil(o.MicCustom) {
		return nil, false
	}
	return o.MicCustom, true
}

// HasMicCustom returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingGet200Response) HasMicCustom() bool {
	if o != nil && !IsNil(o.MicCustom) {
		return true
	}

	return false
}

// SetMicCustom gets a reference to the given ApiDeviceLedsRingGet200ResponseMicCustom and assigns it to the MicCustom field.
func (o *ApiDeviceLedsRingGet200Response) SetMicCustom(v ApiDeviceLedsRingGet200ResponseMicCustom) {
	o.MicCustom = &v
}

func (o ApiDeviceLedsRingGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceLedsRingGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Brightness) {
		toSerialize["brightness"] = o.Brightness
	}
	if !IsNil(o.ShowFarendActivity) {
		toSerialize["showFarendActivity"] = o.ShowFarendActivity
	}
	if !IsNil(o.MicOn) {
		toSerialize["micOn"] = o.MicOn
	}
	if !IsNil(o.MicMute) {
		toSerialize["micMute"] = o.MicMute
	}
	if !IsNil(o.MicCustom) {
		toSerialize["micCustom"] = o.MicCustom
	}
	return toSerialize, nil
}

type NullableApiDeviceLedsRingGet200Response struct {
	value *ApiDeviceLedsRingGet200Response
	isSet bool
}

func (v NullableApiDeviceLedsRingGet200Response) Get() *ApiDeviceLedsRingGet200Response {
	return v.value
}

func (v *NullableApiDeviceLedsRingGet200Response) Set(val *ApiDeviceLedsRingGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceLedsRingGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceLedsRingGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceLedsRingGet200Response(val *ApiDeviceLedsRingGet200Response) *NullableApiDeviceLedsRingGet200Response {
	return &NullableApiDeviceLedsRingGet200Response{value: val, isSet: true}
}

func (v NullableApiDeviceLedsRingGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceLedsRingGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


