/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiFirmwareUpdateStateGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiFirmwareUpdateStateGet200Response{}

// ApiFirmwareUpdateStateGet200Response struct for ApiFirmwareUpdateStateGet200Response
type ApiFirmwareUpdateStateGet200Response struct {
	// The firmware version of the system running at the moment.
	DeviceVersion *string `json:"deviceVersion,omitempty"`
	// The Dante firmware version of the system running at the moment.
	DanteVersion *string `json:"danteVersion,omitempty"`
	State *string `json:"state,omitempty"`
	// Progress in percent
	Progress *int32 `json:"progress,omitempty"`
	// Value is reset to None after reboot and on every start of FW update
	LastStatus *string `json:"lastStatus,omitempty"`
}

// NewApiFirmwareUpdateStateGet200Response instantiates a new ApiFirmwareUpdateStateGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiFirmwareUpdateStateGet200Response() *ApiFirmwareUpdateStateGet200Response {
	this := ApiFirmwareUpdateStateGet200Response{}
	var state string = "Idle"
	this.State = &state
	var progress int32 = 0
	this.Progress = &progress
	var lastStatus string = "None"
	this.LastStatus = &lastStatus
	return &this
}

// NewApiFirmwareUpdateStateGet200ResponseWithDefaults instantiates a new ApiFirmwareUpdateStateGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiFirmwareUpdateStateGet200ResponseWithDefaults() *ApiFirmwareUpdateStateGet200Response {
	this := ApiFirmwareUpdateStateGet200Response{}
	var state string = "Idle"
	this.State = &state
	var progress int32 = 0
	this.Progress = &progress
	var lastStatus string = "None"
	this.LastStatus = &lastStatus
	return &this
}

// GetDeviceVersion returns the DeviceVersion field value if set, zero value otherwise.
func (o *ApiFirmwareUpdateStateGet200Response) GetDeviceVersion() string {
	if o == nil || IsNil(o.DeviceVersion) {
		var ret string
		return ret
	}
	return *o.DeviceVersion
}

// GetDeviceVersionOk returns a tuple with the DeviceVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFirmwareUpdateStateGet200Response) GetDeviceVersionOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceVersion) {
		return nil, false
	}
	return o.DeviceVersion, true
}

// HasDeviceVersion returns a boolean if a field has been set.
func (o *ApiFirmwareUpdateStateGet200Response) HasDeviceVersion() bool {
	if o != nil && !IsNil(o.DeviceVersion) {
		return true
	}

	return false
}

// SetDeviceVersion gets a reference to the given string and assigns it to the DeviceVersion field.
func (o *ApiFirmwareUpdateStateGet200Response) SetDeviceVersion(v string) {
	o.DeviceVersion = &v
}

// GetDanteVersion returns the DanteVersion field value if set, zero value otherwise.
func (o *ApiFirmwareUpdateStateGet200Response) GetDanteVersion() string {
	if o == nil || IsNil(o.DanteVersion) {
		var ret string
		return ret
	}
	return *o.DanteVersion
}

// GetDanteVersionOk returns a tuple with the DanteVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFirmwareUpdateStateGet200Response) GetDanteVersionOk() (*string, bool) {
	if o == nil || IsNil(o.DanteVersion) {
		return nil, false
	}
	return o.DanteVersion, true
}

// HasDanteVersion returns a boolean if a field has been set.
func (o *ApiFirmwareUpdateStateGet200Response) HasDanteVersion() bool {
	if o != nil && !IsNil(o.DanteVersion) {
		return true
	}

	return false
}

// SetDanteVersion gets a reference to the given string and assigns it to the DanteVersion field.
func (o *ApiFirmwareUpdateStateGet200Response) SetDanteVersion(v string) {
	o.DanteVersion = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ApiFirmwareUpdateStateGet200Response) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFirmwareUpdateStateGet200Response) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ApiFirmwareUpdateStateGet200Response) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ApiFirmwareUpdateStateGet200Response) SetState(v string) {
	o.State = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *ApiFirmwareUpdateStateGet200Response) GetProgress() int32 {
	if o == nil || IsNil(o.Progress) {
		var ret int32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFirmwareUpdateStateGet200Response) GetProgressOk() (*int32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *ApiFirmwareUpdateStateGet200Response) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given int32 and assigns it to the Progress field.
func (o *ApiFirmwareUpdateStateGet200Response) SetProgress(v int32) {
	o.Progress = &v
}

// GetLastStatus returns the LastStatus field value if set, zero value otherwise.
func (o *ApiFirmwareUpdateStateGet200Response) GetLastStatus() string {
	if o == nil || IsNil(o.LastStatus) {
		var ret string
		return ret
	}
	return *o.LastStatus
}

// GetLastStatusOk returns a tuple with the LastStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFirmwareUpdateStateGet200Response) GetLastStatusOk() (*string, bool) {
	if o == nil || IsNil(o.LastStatus) {
		return nil, false
	}
	return o.LastStatus, true
}

// HasLastStatus returns a boolean if a field has been set.
func (o *ApiFirmwareUpdateStateGet200Response) HasLastStatus() bool {
	if o != nil && !IsNil(o.LastStatus) {
		return true
	}

	return false
}

// SetLastStatus gets a reference to the given string and assigns it to the LastStatus field.
func (o *ApiFirmwareUpdateStateGet200Response) SetLastStatus(v string) {
	o.LastStatus = &v
}

func (o ApiFirmwareUpdateStateGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiFirmwareUpdateStateGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceVersion) {
		toSerialize["deviceVersion"] = o.DeviceVersion
	}
	if !IsNil(o.DanteVersion) {
		toSerialize["danteVersion"] = o.DanteVersion
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.LastStatus) {
		toSerialize["lastStatus"] = o.LastStatus
	}
	return toSerialize, nil
}

type NullableApiFirmwareUpdateStateGet200Response struct {
	value *ApiFirmwareUpdateStateGet200Response
	isSet bool
}

func (v NullableApiFirmwareUpdateStateGet200Response) Get() *ApiFirmwareUpdateStateGet200Response {
	return v.value
}

func (v *NullableApiFirmwareUpdateStateGet200Response) Set(val *ApiFirmwareUpdateStateGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiFirmwareUpdateStateGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiFirmwareUpdateStateGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiFirmwareUpdateStateGet200Response(val *ApiFirmwareUpdateStateGet200Response) *NullableApiFirmwareUpdateStateGet200Response {
	return &NullableApiFirmwareUpdateStateGet200Response{value: val, isSet: true}
}

func (v NullableApiFirmwareUpdateStateGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiFirmwareUpdateStateGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


