/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioVoiceLiftPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioVoiceLiftPutRequest{}

// ApiAudioVoiceLiftPutRequest struct for ApiAudioVoiceLiftPutRequest
type ApiAudioVoiceLiftPutRequest struct {
	// Threshold in dB
	EmergencyMuteThreshold *int32 `json:"emergencyMuteThreshold,omitempty"`
	// Mute time in s
	EmergencyMuteTime *int32 `json:"emergencyMuteTime,omitempty"`
}

// NewApiAudioVoiceLiftPutRequest instantiates a new ApiAudioVoiceLiftPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioVoiceLiftPutRequest() *ApiAudioVoiceLiftPutRequest {
	this := ApiAudioVoiceLiftPutRequest{}
	return &this
}

// NewApiAudioVoiceLiftPutRequestWithDefaults instantiates a new ApiAudioVoiceLiftPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioVoiceLiftPutRequestWithDefaults() *ApiAudioVoiceLiftPutRequest {
	this := ApiAudioVoiceLiftPutRequest{}
	return &this
}

// GetEmergencyMuteThreshold returns the EmergencyMuteThreshold field value if set, zero value otherwise.
func (o *ApiAudioVoiceLiftPutRequest) GetEmergencyMuteThreshold() int32 {
	if o == nil || IsNil(o.EmergencyMuteThreshold) {
		var ret int32
		return ret
	}
	return *o.EmergencyMuteThreshold
}

// GetEmergencyMuteThresholdOk returns a tuple with the EmergencyMuteThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioVoiceLiftPutRequest) GetEmergencyMuteThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.EmergencyMuteThreshold) {
		return nil, false
	}
	return o.EmergencyMuteThreshold, true
}

// HasEmergencyMuteThreshold returns a boolean if a field has been set.
func (o *ApiAudioVoiceLiftPutRequest) HasEmergencyMuteThreshold() bool {
	if o != nil && !IsNil(o.EmergencyMuteThreshold) {
		return true
	}

	return false
}

// SetEmergencyMuteThreshold gets a reference to the given int32 and assigns it to the EmergencyMuteThreshold field.
func (o *ApiAudioVoiceLiftPutRequest) SetEmergencyMuteThreshold(v int32) {
	o.EmergencyMuteThreshold = &v
}

// GetEmergencyMuteTime returns the EmergencyMuteTime field value if set, zero value otherwise.
func (o *ApiAudioVoiceLiftPutRequest) GetEmergencyMuteTime() int32 {
	if o == nil || IsNil(o.EmergencyMuteTime) {
		var ret int32
		return ret
	}
	return *o.EmergencyMuteTime
}

// GetEmergencyMuteTimeOk returns a tuple with the EmergencyMuteTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioVoiceLiftPutRequest) GetEmergencyMuteTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.EmergencyMuteTime) {
		return nil, false
	}
	return o.EmergencyMuteTime, true
}

// HasEmergencyMuteTime returns a boolean if a field has been set.
func (o *ApiAudioVoiceLiftPutRequest) HasEmergencyMuteTime() bool {
	if o != nil && !IsNil(o.EmergencyMuteTime) {
		return true
	}

	return false
}

// SetEmergencyMuteTime gets a reference to the given int32 and assigns it to the EmergencyMuteTime field.
func (o *ApiAudioVoiceLiftPutRequest) SetEmergencyMuteTime(v int32) {
	o.EmergencyMuteTime = &v
}

func (o ApiAudioVoiceLiftPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioVoiceLiftPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EmergencyMuteThreshold) {
		toSerialize["emergencyMuteThreshold"] = o.EmergencyMuteThreshold
	}
	if !IsNil(o.EmergencyMuteTime) {
		toSerialize["emergencyMuteTime"] = o.EmergencyMuteTime
	}
	return toSerialize, nil
}

type NullableApiAudioVoiceLiftPutRequest struct {
	value *ApiAudioVoiceLiftPutRequest
	isSet bool
}

func (v NullableApiAudioVoiceLiftPutRequest) Get() *ApiAudioVoiceLiftPutRequest {
	return v.value
}

func (v *NullableApiAudioVoiceLiftPutRequest) Set(val *ApiAudioVoiceLiftPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioVoiceLiftPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioVoiceLiftPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioVoiceLiftPutRequest(val *ApiAudioVoiceLiftPutRequest) *NullableApiAudioVoiceLiftPutRequest {
	return &NullableApiAudioVoiceLiftPutRequest{value: val, isSet: true}
}

func (v NullableApiAudioVoiceLiftPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioVoiceLiftPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


