/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAudioOutputsAnalogPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAudioOutputsAnalogPutRequest{}

// ApiAudioOutputsAnalogPutRequest struct for ApiAudioOutputsAnalogPutRequest
type ApiAudioOutputsAnalogPutRequest struct {
	// Gain in dB
	Gain *int32 `json:"gain,omitempty"`
	Switch *string `json:"switch,omitempty"`
}

// NewApiAudioOutputsAnalogPutRequest instantiates a new ApiAudioOutputsAnalogPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAudioOutputsAnalogPutRequest() *ApiAudioOutputsAnalogPutRequest {
	this := ApiAudioOutputsAnalogPutRequest{}
	return &this
}

// NewApiAudioOutputsAnalogPutRequestWithDefaults instantiates a new ApiAudioOutputsAnalogPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAudioOutputsAnalogPutRequestWithDefaults() *ApiAudioOutputsAnalogPutRequest {
	this := ApiAudioOutputsAnalogPutRequest{}
	return &this
}

// GetGain returns the Gain field value if set, zero value otherwise.
func (o *ApiAudioOutputsAnalogPutRequest) GetGain() int32 {
	if o == nil || IsNil(o.Gain) {
		var ret int32
		return ret
	}
	return *o.Gain
}

// GetGainOk returns a tuple with the Gain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsAnalogPutRequest) GetGainOk() (*int32, bool) {
	if o == nil || IsNil(o.Gain) {
		return nil, false
	}
	return o.Gain, true
}

// HasGain returns a boolean if a field has been set.
func (o *ApiAudioOutputsAnalogPutRequest) HasGain() bool {
	if o != nil && !IsNil(o.Gain) {
		return true
	}

	return false
}

// SetGain gets a reference to the given int32 and assigns it to the Gain field.
func (o *ApiAudioOutputsAnalogPutRequest) SetGain(v int32) {
	o.Gain = &v
}

// GetSwitch returns the Switch field value if set, zero value otherwise.
func (o *ApiAudioOutputsAnalogPutRequest) GetSwitch() string {
	if o == nil || IsNil(o.Switch) {
		var ret string
		return ret
	}
	return *o.Switch
}

// GetSwitchOk returns a tuple with the Switch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAudioOutputsAnalogPutRequest) GetSwitchOk() (*string, bool) {
	if o == nil || IsNil(o.Switch) {
		return nil, false
	}
	return o.Switch, true
}

// HasSwitch returns a boolean if a field has been set.
func (o *ApiAudioOutputsAnalogPutRequest) HasSwitch() bool {
	if o != nil && !IsNil(o.Switch) {
		return true
	}

	return false
}

// SetSwitch gets a reference to the given string and assigns it to the Switch field.
func (o *ApiAudioOutputsAnalogPutRequest) SetSwitch(v string) {
	o.Switch = &v
}

func (o ApiAudioOutputsAnalogPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAudioOutputsAnalogPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gain) {
		toSerialize["gain"] = o.Gain
	}
	if !IsNil(o.Switch) {
		toSerialize["switch"] = o.Switch
	}
	return toSerialize, nil
}

type NullableApiAudioOutputsAnalogPutRequest struct {
	value *ApiAudioOutputsAnalogPutRequest
	isSet bool
}

func (v NullableApiAudioOutputsAnalogPutRequest) Get() *ApiAudioOutputsAnalogPutRequest {
	return v.value
}

func (v *NullableApiAudioOutputsAnalogPutRequest) Set(val *ApiAudioOutputsAnalogPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAudioOutputsAnalogPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAudioOutputsAnalogPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAudioOutputsAnalogPutRequest(val *ApiAudioOutputsAnalogPutRequest) *NullableApiAudioOutputsAnalogPutRequest {
	return &NullableApiAudioOutputsAnalogPutRequest{value: val, isSet: true}
}

func (v NullableApiAudioOutputsAnalogPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAudioOutputsAnalogPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


