/*
TCC M 3rd party API Release

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiDeviceLedsRingPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiDeviceLedsRingPutRequest{}

// ApiDeviceLedsRingPutRequest struct for ApiDeviceLedsRingPutRequest
type ApiDeviceLedsRingPutRequest struct {
	// The brightness of the led ring can be controlled in 6 steps, where 0 is off and 5 is full brightness.
	Brightness *int32 `json:"brightness,omitempty"`
	ShowFarendActivity *bool `json:"showFarendActivity,omitempty"`
	MicOn *ApiDeviceLedsRingPutRequestMicOn `json:"micOn,omitempty"`
	MicMute *ApiDeviceLedsRingPutRequestMicOn `json:"micMute,omitempty"`
	MicCustom *ApiDeviceLedsRingPutRequestMicCustom `json:"micCustom,omitempty"`
}

// NewApiDeviceLedsRingPutRequest instantiates a new ApiDeviceLedsRingPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiDeviceLedsRingPutRequest() *ApiDeviceLedsRingPutRequest {
	this := ApiDeviceLedsRingPutRequest{}
	return &this
}

// NewApiDeviceLedsRingPutRequestWithDefaults instantiates a new ApiDeviceLedsRingPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiDeviceLedsRingPutRequestWithDefaults() *ApiDeviceLedsRingPutRequest {
	this := ApiDeviceLedsRingPutRequest{}
	return &this
}

// GetBrightness returns the Brightness field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequest) GetBrightness() int32 {
	if o == nil || IsNil(o.Brightness) {
		var ret int32
		return ret
	}
	return *o.Brightness
}

// GetBrightnessOk returns a tuple with the Brightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequest) GetBrightnessOk() (*int32, bool) {
	if o == nil || IsNil(o.Brightness) {
		return nil, false
	}
	return o.Brightness, true
}

// HasBrightness returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequest) HasBrightness() bool {
	if o != nil && !IsNil(o.Brightness) {
		return true
	}

	return false
}

// SetBrightness gets a reference to the given int32 and assigns it to the Brightness field.
func (o *ApiDeviceLedsRingPutRequest) SetBrightness(v int32) {
	o.Brightness = &v
}

// GetShowFarendActivity returns the ShowFarendActivity field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequest) GetShowFarendActivity() bool {
	if o == nil || IsNil(o.ShowFarendActivity) {
		var ret bool
		return ret
	}
	return *o.ShowFarendActivity
}

// GetShowFarendActivityOk returns a tuple with the ShowFarendActivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequest) GetShowFarendActivityOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowFarendActivity) {
		return nil, false
	}
	return o.ShowFarendActivity, true
}

// HasShowFarendActivity returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequest) HasShowFarendActivity() bool {
	if o != nil && !IsNil(o.ShowFarendActivity) {
		return true
	}

	return false
}

// SetShowFarendActivity gets a reference to the given bool and assigns it to the ShowFarendActivity field.
func (o *ApiDeviceLedsRingPutRequest) SetShowFarendActivity(v bool) {
	o.ShowFarendActivity = &v
}

// GetMicOn returns the MicOn field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequest) GetMicOn() ApiDeviceLedsRingPutRequestMicOn {
	if o == nil || IsNil(o.MicOn) {
		var ret ApiDeviceLedsRingPutRequestMicOn
		return ret
	}
	return *o.MicOn
}

// GetMicOnOk returns a tuple with the MicOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequest) GetMicOnOk() (*ApiDeviceLedsRingPutRequestMicOn, bool) {
	if o == nil || IsNil(o.MicOn) {
		return nil, false
	}
	return o.MicOn, true
}

// HasMicOn returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequest) HasMicOn() bool {
	if o != nil && !IsNil(o.MicOn) {
		return true
	}

	return false
}

// SetMicOn gets a reference to the given ApiDeviceLedsRingPutRequestMicOn and assigns it to the MicOn field.
func (o *ApiDeviceLedsRingPutRequest) SetMicOn(v ApiDeviceLedsRingPutRequestMicOn) {
	o.MicOn = &v
}

// GetMicMute returns the MicMute field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequest) GetMicMute() ApiDeviceLedsRingPutRequestMicOn {
	if o == nil || IsNil(o.MicMute) {
		var ret ApiDeviceLedsRingPutRequestMicOn
		return ret
	}
	return *o.MicMute
}

// GetMicMuteOk returns a tuple with the MicMute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequest) GetMicMuteOk() (*ApiDeviceLedsRingPutRequestMicOn, bool) {
	if o == nil || IsNil(o.MicMute) {
		return nil, false
	}
	return o.MicMute, true
}

// HasMicMute returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequest) HasMicMute() bool {
	if o != nil && !IsNil(o.MicMute) {
		return true
	}

	return false
}

// SetMicMute gets a reference to the given ApiDeviceLedsRingPutRequestMicOn and assigns it to the MicMute field.
func (o *ApiDeviceLedsRingPutRequest) SetMicMute(v ApiDeviceLedsRingPutRequestMicOn) {
	o.MicMute = &v
}

// GetMicCustom returns the MicCustom field value if set, zero value otherwise.
func (o *ApiDeviceLedsRingPutRequest) GetMicCustom() ApiDeviceLedsRingPutRequestMicCustom {
	if o == nil || IsNil(o.MicCustom) {
		var ret ApiDeviceLedsRingPutRequestMicCustom
		return ret
	}
	return *o.MicCustom
}

// GetMicCustomOk returns a tuple with the MicCustom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiDeviceLedsRingPutRequest) GetMicCustomOk() (*ApiDeviceLedsRingPutRequestMicCustom, bool) {
	if o == nil || IsNil(o.MicCustom) {
		return nil, false
	}
	return o.MicCustom, true
}

// HasMicCustom returns a boolean if a field has been set.
func (o *ApiDeviceLedsRingPutRequest) HasMicCustom() bool {
	if o != nil && !IsNil(o.MicCustom) {
		return true
	}

	return false
}

// SetMicCustom gets a reference to the given ApiDeviceLedsRingPutRequestMicCustom and assigns it to the MicCustom field.
func (o *ApiDeviceLedsRingPutRequest) SetMicCustom(v ApiDeviceLedsRingPutRequestMicCustom) {
	o.MicCustom = &v
}

func (o ApiDeviceLedsRingPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiDeviceLedsRingPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Brightness) {
		toSerialize["brightness"] = o.Brightness
	}
	if !IsNil(o.ShowFarendActivity) {
		toSerialize["showFarendActivity"] = o.ShowFarendActivity
	}
	if !IsNil(o.MicOn) {
		toSerialize["micOn"] = o.MicOn
	}
	if !IsNil(o.MicMute) {
		toSerialize["micMute"] = o.MicMute
	}
	if !IsNil(o.MicCustom) {
		toSerialize["micCustom"] = o.MicCustom
	}
	return toSerialize, nil
}

type NullableApiDeviceLedsRingPutRequest struct {
	value *ApiDeviceLedsRingPutRequest
	isSet bool
}

func (v NullableApiDeviceLedsRingPutRequest) Get() *ApiDeviceLedsRingPutRequest {
	return v.value
}

func (v *NullableApiDeviceLedsRingPutRequest) Set(val *ApiDeviceLedsRingPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiDeviceLedsRingPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiDeviceLedsRingPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiDeviceLedsRingPutRequest(val *ApiDeviceLedsRingPutRequest) *NullableApiDeviceLedsRingPutRequest {
	return &NullableApiDeviceLedsRingPutRequest{value: val, isSet: true}
}

func (v NullableApiDeviceLedsRingPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiDeviceLedsRingPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


